workflows:
  android-app:
    name: Build HealthConnect APK
    environment:
      flutter: false
      vars:
        JAVA_HOME: /opt/android-studio/jre
    scripts:
      - name: Clean project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sujalgoel19@yahoo.com
          
