workflows:
  build-android:
    name: Build Android APK
    max_build_duration: 15
    instance_type: mac_mini_m1

    environment:
      vars:
        GRADLE_OPTS: "-Xmx4096m -Dorg.gradle.jvmargs=-Xmx4096m"

    scripts:
      - name: Make gradlew executable
        script: chmod +x ./gradlew
      - name: Clean the project
        script: ./gradlew clean
      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
