workflows:
  android-app:
    name: Build HealthConnect APK
    environment:
      vars:
        JAVA_HOME: /opt/android-studio/jre
      android:
        sdk: 33
    scripts:
      - name: Set up Gradle
        script: |
          ./gradlew clean
      - name: Build Debug APK
        script: |
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - sujalgoel19@yahoo.com
